// <auto-generated />
using System;
using CafeAvalonia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeAvalonia.Migrations
{
    [DbContext(typeof(BdcafeContext))]
    [Migration("20251203173819_Initial_Clean")]
    partial class Initial_Clean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeAvalonia.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Incridients")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incridients");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("dishes_pkey");

                    b.ToTable("dishes", (string)null);
                });

            modelBuilder.Entity("CafeAvalonia.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<string>("ScanContract")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scan_contract");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("speciality");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("employee_pkey");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("CafeAvalonia.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientsCount")
                        .HasColumnType("integer")
                        .HasColumnName("clients_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("FkDishesid")
                        .HasColumnType("integer")
                        .HasColumnName("fk_dishesid");

                    b.Property<int?>("FkEmployeeid")
                        .HasColumnType("integer")
                        .HasColumnName("fk_employeeid");

                    b.Property<decimal>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.HasKey("Id")
                        .HasName("Order_pkey");

                    b.HasIndex("FkDishesid");

                    b.HasIndex("FkEmployeeid");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("CafeAvalonia.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFinis")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_finis");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_start");

                    b.HasKey("Id")
                        .HasName("shifts_pkey");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("CafeAvalonia.Models.Shiftassignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FkEmployeeid")
                        .HasColumnType("integer")
                        .HasColumnName("fk_employeeid");

                    b.Property<int?>("FkShiftsid")
                        .HasColumnType("integer")
                        .HasColumnName("fk_shiftsid");

                    b.HasKey("Id")
                        .HasName("shiftassignment_pkey");

                    b.HasIndex("FkEmployeeid");

                    b.HasIndex("FkShiftsid");

                    b.ToTable("shiftassignment", (string)null);
                });

            modelBuilder.Entity("CafeAvalonia.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<int?>("FkEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_employee_id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("FkEmployeeId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CafeAvalonia.Models.Order", b =>
                {
                    b.HasOne("CafeAvalonia.Models.Dish", "FkDishes")
                        .WithMany("Orders")
                        .HasForeignKey("FkDishesid")
                        .HasConstraintName("Order_fk_dishesid_fkey");

                    b.HasOne("CafeAvalonia.Models.Employee", "FkEmployee")
                        .WithMany("Orders")
                        .HasForeignKey("FkEmployeeid")
                        .HasConstraintName("Order_fk_employeeid_fkey");

                    b.Navigation("FkDishes");

                    b.Navigation("FkEmployee");
                });

            modelBuilder.Entity("CafeAvalonia.Models.Shiftassignment", b =>
                {
                    b.HasOne("CafeAvalonia.Models.Employee", "FkEmployee")
                        .WithMany("Shiftassignments")
                        .HasForeignKey("FkEmployeeid")
                        .HasConstraintName("shiftassignment_fk_employeeid_fkey");

                    b.HasOne("CafeAvalonia.Models.Shift", "FkShifts")
                        .WithMany("Shiftassignments")
                        .HasForeignKey("FkShiftsid")
                        .HasConstraintName("shiftassignment_fk_shiftsid_fkey");

                    b.Navigation("FkEmployee");

                    b.Navigation("FkShifts");
                });

            modelBuilder.Entity("CafeAvalonia.Models.User", b =>
                {
                    b.HasOne("CafeAvalonia.Models.Employee", "FkEmployee")
                        .WithMany("Users")
                        .HasForeignKey("FkEmployeeId")
                        .HasConstraintName("users_fk_employee_id_fkey");

                    b.Navigation("FkEmployee");
                });

            modelBuilder.Entity("CafeAvalonia.Models.Dish", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CafeAvalonia.Models.Employee", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Shiftassignments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CafeAvalonia.Models.Shift", b =>
                {
                    b.Navigation("Shiftassignments");
                });
#pragma warning restore 612, 618
        }
    }
}
